<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #222; margin: 24px; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        .muted { color: #666; }
        .header { display: flex; justify-content: space-between; margin-bottom: 20px; }
        .box { border: 1px solid #ddd; padding: 12px; border-radius: 6px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #f5f5f5; }
        .right { text-align: right; }
        .totals td { border: none; padding: 4px 8px; }
        .grand { font-size: 14px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1>{{ $tenant?->business_name ?? 'Garage' }}</h1>
            @if($tenant?->address)
                <p class="muted">{{ $tenant->address }}{{ $tenant->city ? ', '.$tenant->city : '' }}{{ $tenant->pincode ? ' - '.$tenant->pincode : '' }}</p>
            @endif
            @if($tenant?->gst_number)
                <p class="muted">GSTIN: {{ $tenant->gst_number }}</p>
            @endif
            @if($tenant?->phone)
                <p class="muted">Phone: {{ $tenant->phone }}</p>
            @endif
        </div>
        <div class="right">
            <p><strong>Tax Invoice</strong></p>
            <p>{{ $invoice->invoice_number }}</p>
            <p class="muted">Date: {{ $invoice->issued_date?->format('d M Y') }}</p>
            @if($invoice->job)
                <p class="muted">Job: {{ $invoice->job->job_number }}</p>
            @endif
        </div>
    </div>

    <div class="box">
        <strong>Bill To</strong><br>
        {{ $invoice->customer?->full_name }}<br>
        @if($invoice->customer?->phone_primary)
            {{ $invoice->customer->phone_primary }}<br>
        @endif
        @if($invoice->vehicle)
            Vehicle: {{ $invoice->vehicle->registration_number }} — {{ $invoice->vehicle->maker }} {{ $invoice->vehicle->model }}
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Description</th>
                <th class="right">Qty</th>
                <th class="right">Rate (₹)</th>
                <th class="right">Tax (₹)</th>
                <th class="right">Amount (₹)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoice->items as $i => $item)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $item->name }}</td>
                    <td class="right">{{ number_format((float) $item->quantity, 2) }}</td>
                    <td class="right">{{ number_format((float) $item->unit_price, 2) }}</td>
                    <td class="right">{{ number_format((float) $item->tax_amount, 2) }}</td>
                    <td class="right">{{ number_format((float) $item->total_amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals" style="width: 280px; margin-left: auto; margin-top: 16px;">
        <tr><td class="right">Subtotal</td><td class="right">₹{{ number_format((float) $invoice->subtotal, 2) }}</td></tr>
        <tr><td class="right">Tax</td><td class="right">₹{{ number_format((float) $invoice->tax_total, 2) }}</td></tr>
        @if((float) $invoice->discount_total > 0)
            <tr><td class="right">Discount</td><td class="right">-₹{{ number_format((float) $invoice->discount_total, 2) }}</td></tr>
        @endif
        <tr class="grand"><td class="right">Grand Total</td><td class="right">₹{{ number_format((float) $invoice->grand_total, 2) }}</td></tr>
        <tr><td class="right">Paid</td><td class="right">₹{{ number_format((float) $invoice->amount_paid, 2) }}</td></tr>
        <tr class="grand"><td class="right">Balance Due</td><td class="right">₹{{ number_format((float) $invoice->balance_due, 2) }}</td></tr>
    </table>

    @if($invoice->customer_notes)
        <div class="box" style="margin-top: 20px;">
            <strong>Notes</strong><br>
            {{ $invoice->customer_notes }}
        </div>
    @endif

    @if($invoice->terms_conditions)
        <p class="muted" style="margin-top: 16px;">{{ $invoice->terms_conditions }}</p>
    @endif

    <p class="muted" style="margin-top: 24px;">Generated by Pro Garage OS · {{ now()->format('d M Y H:i') }}</p>
</body>
</html>
